# Generated by Django 4.0.6 on 2022-07-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.DateField()),
                ('price', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='H', max_length=1)),
            ],
        ),
    ]
