# Generated by Django 4.0.6 on 2022-07-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mods'),
    ]

    operations = [
        migrations.AddField(
            model_name='mods',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mods',
            name='mod',
            field=models.CharField(max_length=100),
        ),
    ]
