# Generated by Django 4.0.6 on 2022-07-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='shop',
            field=models.ManyToManyField(to='main_app.shop'),
        ),
    ]
